name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  automation-test-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Unit Tests
        run: npx vitest --no-watch
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
      - name: Run E2E Tests
        run: npx start-server-and-test "vite --host 0.0.0.0" http-get://localhost:5173 "cypress run"
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
